# Generated by Django 5.2.2 on 2025-06-10 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Poketype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sprite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_default', models.URLField()),
                ('front_shiny', models.URLField()),
                ('front_female', models.URLField()),
                ('front_shiny_female', models.URLField()),
                ('back_default', models.URLField()),
                ('back_female', models.URLField()),
                ('back_shiny_female', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='EvolutionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_nodes', to='pokedex.evolutionnode')),
            ],
        ),
        migrations.CreateModel(
            name='EvolutionTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pokedex.evolutionnode')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('evolution_tree', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pokemon', to='pokedex.evolutiontree')),
                ('moves', models.ManyToManyField(related_name='pokemon', to='pokedex.move')),
                ('types', models.ManyToManyField(related_name='pokemon', to='pokedex.poketype')),
                ('sprite', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon', to='pokedex.sprite')),
            ],
        ),
        migrations.AddField(
            model_name='evolutionnode',
            name='pokemon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pokedex.pokemon'),
        ),
        migrations.AddField(
            model_name='move',
            name='poketype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='pokedex.poketype'),
        ),
    ]
