# Generated by Django 5.2.2 on 2025-06-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprite',
            name='back_default',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='sprite',
            name='back_female',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='sprite',
            name='back_shiny_female',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='sprite',
            name='front_default',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='sprite',
            name='front_female',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='sprite',
            name='front_shiny',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='sprite',
            name='front_shiny_female',
            field=models.URLField(null=True),
        ),
    ]
