# Generated by Django 5.2.2 on 2025-06-10 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_sprite_back_default_alter_sprite_back_female_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='evolution_tree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pokemon', to='pokedex.evolutiontree'),
        ),
    ]
