# Generated by Django 5.2.2 on 2025-06-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_alter_pokemon_evolution_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprite',
            name='back_shiny',
            field=models.URLField(null=True),
        ),
    ]
